# Generated by Django 3.1.7 on 2021-03-06 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210306_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 6, 13, 55, 55, 518979)),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(blank=True, default=40, null=True),
        ),
    ]
