# Generated by Django 3.1.7 on 2021-03-06 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210306_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 6, 13, 56, 23, 878156)),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
