# Generated by Django 3.1.7 on 2021-03-07 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20210306_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 7, 14, 19, 0, 546020)),
        ),
    ]
